### ISSUE TITLE
1.3.4 Wireframe Design

### ISSUE THREAD

**Issue by kennethwyq** [JGL20/INF-2001-TEAM-PROJECT-P7-3#47]
1. Task title ID: 1.3.4

2. What is the task about?
This task involves creating wireframe designs for the user interface of the workload management system. The wireframe designs are visual representation of the layout and functionality of the system and will be used as the reference for the user interface during development.

3. What are the goals of the task?
The goal of this task is to define the layout and structure of the user interface. 

4. Success or completion criteria.
This task is completed when the following sub-tasks are completed:
- task 1.3.4.1
- task 1.3.4.2
- task 1.3.4.3
- task 1.3.4.4
- task 1.3.4.5

5. Allocated time
3 days

6. Start date and end date of the issue/task
Start Date: 15/09/2023
End Date: 17/09/2023

7. Who is the owner? The owner is the person in-charge of the task and the task should be created and maintained by the owner.
Task Owner: Kenneth Wang

8. The status of the task. This is usually "To-Do" initially.
In-Progress

9. What is the Priority of the task?
Medium

**Comment by kennethwyq** [comment]
1. Describe the work done in detail.
task 1.3.4.1 has been completed

2. Has this work been committed to the repo?
No.

3. How does the work affect the completion deadline.
No.

4. Are there any changes to the success or completion criteria of the task? If yes, please describe the details.
No.

5. Start date and end date of the work done for this comment.
Start Date: 17/09/2023
End Date: 17/09/2023

**Comment by kennethwyq** [comment]
1. Describe the work done in detail.
task 1.3.4.3 has been completed

2. Has this work been committed to the repo?
No.

3. How does the work affect the completion deadline.
No.

4. Are there any changes to the success or completion criteria of the task? If yes, please describe the details.
No.

5. Start date and end date of the work done for this comment.
Start Date: 17/09/2023
End Date: 17/09/2023

**Comment by Edkaa** [comment]
**Describe the work done in detail.**
Task 1.3.4.2 has been completed


**Has this work been committed to the repo?**
No.

**How does the work affect the completion deadline.**
No.

**Are there any changes to the success or completion criteria of the task? If yes, please describe the details.**
No.

**Start date and end date of the work done for this comment.**
Start Date: 01/09/2023
End Date: 11/09/2023

**Comment by rachelpyx** [comment]
Describe the work done in detail.
Task 1.3.4.4 has been completed

Has this work been committed to the repo?
No.

How does the work affect the completion deadline.
No.

Are there any changes to the success or completion criteria of the task? If yes, please describe the details.
No.

Start date and end date of the work done for this comment.
Start Date: 15/09/2023
End Date: 17/09/2023

**Comment by rachelpyx** [comment]
Describe the work done in detail.
Task 1.3.4.5 has been completed

Has this work been committed to the repo?
No.

How does the work affect the completion deadline.
No.

Are there any changes to the success or completion criteria of the task? If yes, please describe the details.
No.

Start date and end date of the work done for this comment.
Start Date: 15/09/2023
End Date: 17/09/2023

**Comment by kennethwyq** [comment]
Describe the work done in detail.
all sub task has been completed

Has this work been committed to the repo?
No.

How does the work affect the completion deadline.
No.

Are there any changes to the success or completion criteria of the task? If yes, please describe the details.
No.

Start date and end date of the work done for this comment.
Start Date: 17/09/2023
End Date: 17/09/2023
