### ISSUE TITLE
1.4.1 Software Estimation

### ISSUE THREAD

**Issue by kennethwyq** [JGL20/INF-2001-TEAM-PROJECT-P7-3#54]
1. Task title ID: 1.4.1

2. What is the task about?
This task involves estimating the resources, time, effort, and cost required for the project.

3. What are the goals of the task?
The goals of this task is to provide a realistic estimate of the duration and cost of the project.

4. Success or completion criteria.
This task is completed when the following sub-tasks are completed:

- task 1.4.1.1
- task 1.4.1.2

5. Allocated time
5 days

6. Start date and end date of the issue/task
Start Date: 18/09/2023
End Date: 22/09/2023

7. Who is the owner? The owner is the person in-charge of the task and the task should be created and maintained by the owner.
Task Owner: Kenneth Wang

8. The status of the task. This is usually "To-Do" initially.
Done

9. What is the Priority of the task?
High

**Comment by Edkaa** [comment]
Describe the work done in detail.
Task 1.4.1.2 completed

Has this work been committed to the repo?
No.

How does the work affect the completion deadline.
No.

Are there any changes to the success or completion criteria of the task? If yes, please describe the details.
No.

Start date and end date of the work done for this comment.
Start Date: 19/09/2023
End Date: 19/09/2023

**Comment by kennethwyq** [comment]
1. Describe the work done in detail.
Task 1.4.1.1 completed

2. Has this work been committed to the repo?
No.

3. How does the work affect the completion deadline.
No.

4. Are there any changes to the success or completion criteria of the task? If yes, please describe the details.
No.

5. Start date and end date of the work done for this comment.
Start Date: 18/09/2023
End Date: 18/09/2023

**Comment by kennethwyq** [comment]
Describe the work done in detail.
all sub tasks completed

Has this work been committed to the repo?
No.

How does the work affect the completion deadline.
No.

Are there any changes to the success or completion criteria of the task? If yes, please describe the details.
No.

Start date and end date of the work done for this comment.
Start Date: 19/09/2023
End Date: 19/09/2023
