### ISSUE TITLE
2.1 Design Specification

### ISSUE THREAD

**Issue by tszehui** [JGL20/INF-2001-TEAM-PROJECT-P7-3#64]
1. Task title ID: 2.1

2. What is the task about?
     Go through in details on how to craft out the diagrams

3. What are the goals of the task?
    finish up the different diagrams

4. Success of completion criteria
    diagrams are completed

5. Allocated time
    14 day

6. Start date and end date of the issue/task:
    Start Date: 25/9/2023
    End Date: 12/10/2023

7. Who is the owner? The owner is the person in-charge of the task and the task should be created and maintained by the owner.
    Task Owner: Toh Sze Hui

8. The status of the task. This is usually "To-Do" initially.
    Done

9. What is the priority of the task?
    High

**Comment by Edkaa** [comment]
Describe the work done in detail.
Task 2.1.2 completed

Has this work been committed to the repo?
No.

How does the work affect the completion deadline.
No.

Are there any changes to the success or completion criteria of the task? If yes, please describe the details.
No.

Start date and end date of the work done for this comment.
Start Date: 29/09/2023
End Date: 04/10/2023
